### ISSUE TITLE
--brain-client: command not found

### ISSUE THREAD

**Issue by barrett092** [singe/hashcat-brain#1]
--brain-client: command not found

Getting this error when trying to run the wrapper. 
I have it in the same directory as hashcat.

**Comment by barrett092** [comment]
Wait I fixed it. 

Modified the script to put ./ in front of hashcat in line 10.

**Comment by singe** [comment]
Best to make sure it’s in your path, that way you can control which you’re launching from an environment variable rather than editing the script.
